add function clone, rmcommit, rmimage to ln-image

diff --git a/usr/bin/ln-image b/usr/bin/ln-image
--- a/usr/bin/ln-image
+++ b/usr/bin/ln-image
@@ -16,7 +16,7 @@ CACHE=${IMAGES}/.cache
 if [ -f ${CACHE} ]; then
    . ${CACHE}
 else
-   LASTIMAGE=$(find  ${IMAGES}  -maxdepth 1 -name "*-diff" -type d -exec basename \{\} \; | sed 's/-diff//' | sort | head -n1)
+   LASTIMAGE=$(find  ${IMAGES}  -maxdepth 1 -type d -exec basename \{\} \; | sed 's/-diff//' | sort | head -n1)
    [ -n "${LASTIMAGE}" ] && echo "LASTIMAGE=${LASTIMAGE}" > ${CACHE}
 fi
 
@@ -39,19 +39,29 @@ logo
 
   cat << EOF
     Options:
-        --list: list available images
-        --name <image_name>        edit client image
-        --commit <image_name>      commit image changes
-        --rollback <image_name>    rollback image changes
-        --new-image <image_name>  --create: create image
-        --backup <image_name>      build initial install image
-        --iso  		build boot iso image
-        --help : show this messge  
+	Get info
+        --list: 		   		list available images
+	--lstch <image_name>			show differents from image and latest commit
+	--lstcm <image_name>			list of all commit 
+
+	Edit and create
+        --name <image_name>        		edit client image
+        --commit <image_name>      		commit image changes
+        --rollback <image_name>    		rollback image changes
+        --new-image <image_name>  --create: 	create image
+	--clone <image_name> <new_image>	create new image from exist image without commit 
+	--rmcommit <image_name> 		remove latest commit
+	--rmimage <image>			remove image
+
+        Tools for client install
+	--backup <image_name>      		build initial install image
+        --iso  					build boot iso image
+        --help : 				show this messge  
 EOF
 }
 
 SHORTOPTS="hvn:"
-LONGOPTS="help,version,backup,commit,snap,name:,list,iso,rollback,create,arch:,distr:,new-image:,create-states:,cache"
+LONGOPTS="help,version,backup,commit,snap,name:,list,iso,rmcommit,rmimage,clone,rollback,lstch,lstcm,create,arch:,distr:,new-image:,create-states:,cache"
 
 ARGS=$(getopt -s bash --options $SHORTOPTS --longoptions $LONGOPTS --name $PROGNAME -- "$@" )
 eval set -- "$ARGS"
@@ -331,24 +341,78 @@ do_backup() {
     
 }
 
+clone() {
+set -x
+    FROM=$1
+    TO=$2
+    zfs send $(zfs list -t snapshot -o name | grep ${FROM} | tail -1) | zfs recv ${LNPZFS}/${LNVZFS}/${LNIMAGES}/${TO}
+    echo "update etc/fstab and /etc/schroot/schroot.conf"
+
+}
 
 do_chroot() {
     NAME=$1
-    cd ~
+    cd /
     . /etc/default/livenet
     
     schroot -c $NAME
   
- #   chroot ${IMAGES}/${NAME}
  
 }
-showchange(){
-    IMAGE=$2
-    LAST2=$(zfs list -t snapshot -o name | grep ${IMAGE} | tail -2 | head -1)
-    LAST=$(zfs list -t snapshot -o name | grep ${IMAGE} | tail -1)
-    
-    zfs diff ${LAST2} ${LAST} >> ${BASE}/${IMAGE}.changes
 
+rmimage() {
+
+    NAME=$1
+    TEST=$(zfs list | grep ${NAME})
+    if [ -n "$TEST" ]; then
+	umount ${BASE}/images/${NAME}/boot >> /dev/null 2>&1
+	zfs umount ${LNPZFS}/${LNVZFS}/${LNIMAGES}/${NAME}
+    	zfs destroy -r ${LNPZFS}/${LNVZFS}/${LNIMAGES}/${NAME}
+   	if [ -d ${INCREASES}/${NAME} ]; then
+		rm -r ${INCREASES}/${NAME}
+	fi
+	if [ -d ${BACKUP}/${NAME} ]; then
+		rm -r ${BACKUP}/${NAME}
+	fi
+	echo "please update /etc/fstab and /etc/schroot/schroot.conf"
+    else
+	echo "$TEST not exist"
+    fi
+}
+
+
+rmcommit() {
+     NAME=$1
+     TEST=$(zfs list -t snapshot -o name | grep ${NAME})
+     if [ -n "$TEST" ]; then
+	
+	T2=$(zfs list -t snapshot -o name | grep ${NAME} | tail -2 | head -1 | cut -d"@" -f2)
+	T=$(zfs list -t snapshot -o name | grep ${NAME} | tail -1 | cut -d"@" -f2)
+	if [ ${T2} -ne ${T} ] && [ -n $T ] && [ -n $T2 ]; then
+		rm ${INCREASES}/${NAME}/${T}.snapshot.gz
+        	zfs destroy -r $(zfs list -t snapshot -o name | grep ${NAME} | tail -1 )
+        	echo "please update /etc/fstab and /etc/schroot/schroot.conf"
+	fi
+    else
+        echo "$TEST not exist"
+    fi
+
+}
+do_lstcm() {
+   NAME=$1
+   echo "List of all commit for $NAME "
+   zfs list -t snapshot -o name | grep ${NAME}
+}
+showchange(){
+    IMAGE=$1
+    #LAST2=$(zfs list -t snapshot -o name | grep ${IMAGE} | tail -2 | head -1)
+    
+    LAST2=$(zfs list -t snapshot -o name | grep ${IMAGE} | tail -1)
+    LAST=$(zfs list -o name | grep ${IMAGE})
+    zfs diff ${LAST2} ${LAST} > ${BASE}/${IMAGE}.changes
+    cat ${BASE}/${IMAGE}.changes
+    echo ""
+    echo "You can read this output here: ${BASE}/${IMAGE}.changes"
 }
 #show list of images
 do_list() {
@@ -400,7 +464,7 @@ do_commit() {
     LAST2=$(zfs list -t snapshot -o name | grep ${IMAGE} | tail -2 | head -1)
     LAST=$(zfs list -t snapshot -o name | grep ${IMAGE} | tail -1)
      
-   if [ $( zfs diff ${LAST2} ${LAST} | wc -l ) -lt 1 ]; then
+   if [ $( zfs diff ${LAST2} ${LAST} | wc -l ) -lt 4  ]; then
 	zfs destroy ${LNPZFS}/${LNVZFS}/${LNIMAGES}/${IMAGE}@${timestamp}
         echo "Commit is empty"
    	exit 1
@@ -575,7 +639,59 @@ while true; do
         fi
         echo "LASTIMAGE=${NAME}" > ${CACHE}
         do_chroot $NAME
-        ;;
+        exit 0
+	;;
+      --lstcm)
+	shift
+	shift
+	NAME=$1
+	if [ -z $NAME ]; then
+		NAME=$LASTIMAGE
+	fi
+	if [ ! -d ${IMAGES}/${NAME} ]; then
+            echo "ERRORE: ${IMAGES}/${NAME} not present"
+            exit 1
+	fi
+        echo "LASTIMAGE=${NAME}" > ${CACHE}
+
+	do_lstcm $NAME
+	exit 0
+	;;
+      --rmimage)
+	shift
+	shift
+	NAME=$1
+	if [ -z $NAME ]; then
+		echo "image name empty. Please retry with ln-image --rmimage <image name>"
+		exit 1
+	fi
+	if [ ! -d ${IMAGES}/${NAME} ]; then
+            echo "ERRORE: ${IMAGES}/${NAME} not present"
+            exit 1
+	fi
+        #echo "LASTIMAGE=${NAME}" > ${CACHE}
+
+	rmimage $NAME
+	exit 0
+	;;
+      --rmcommit)
+	shift
+	shift
+	NAME=$1
+	if [ -z $NAME ]; then
+		echo "image name empty. Please retry with ln-image --rmimage <image name>"
+		exit 1
+	fi
+	if [ ! -d ${IMAGES}/${NAME} ]; then
+            echo "ERRORE: ${IMAGES}/${NAME} not present"
+            exit 1
+	fi
+        #echo "LASTIMAGE=${NAME}" > ${CACHE}
+
+	rmcommit $NAME
+	exit 0
+	;;
+
       --cache)
         COPY_FROM_CACHE=true
         ;;
@@ -593,9 +709,42 @@ while true; do
         exit 0
         ;;
       --rollback)
+	shift
+	shift
+	NAME=$1
+	if [ -z $NAME ]; then
+		NAME=$LASTIMAGE
+	fi
+
+
+        if [ ! -d ${IMAGES}/${NAME} ]; then
+            echo "ERRORE: ${IMAGES}/${NAME} not present"
+            exit 1
+        fi
         do_reset ${NAME}
         exit 0
         ;;
+      --clone)
+	set -x
+	shift
+	shift
+	FROM=$1
+	TO=$2
+	if [ -n $FROM ] && [ -n $TO ]; then
+	        if [ -d ${IMAGES}/${FROM} ]; then
+		           clone ${FROM} ${TO}
+		else
+        	    echo "ERRORE: ${IMAGES}/${NAME} not present"
+            	    exit 1
+
+        	fi
+        fi
+        exit 0
+        ;;
+      --lstch)
+        showchange ${NAME}
+        exit 0
+	;;
       --returngold)
         do_go_gold ${NAME}
         exit 0
@@ -630,7 +779,7 @@ while true; do
             echo "Error: bad argument"
             exit 1
         fi
-        usage
+#        usage
         break
         ;;
    esac
